# Generated by Django 5.1.6 on 2025-03-05 04:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to='paginas/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
