# Generated by Django 5.1.6 on 2025-03-06 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
